/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.aaron.view;

import java.util.List;
import mx.itson.aaron.controller.ProductController;
import mx.itson.aaron.model.Category;
import mx.itson.aaron.model.Product;

/**
 *
 * @author Daniel
 */
public class Edit extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Edit.class.getName());
    private ProductController productController;
    private Product productoEditando; // null si estamos en modo AGREGAR
    private InventoryAdmin inventoryAdmin;
    
    /**
     * Creates new form Edit
     */
    public Edit() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    //
    //Constructor principal.
    
    //inventoryAdmin  referencia al padre para refrescar la tabla al guardar
    //producto        null = modo AGREGAR, producto cargado = modo EDITAR
    //productController  controlador compartido
    public Edit(InventoryAdmin inventoryAdmin, Product producto, ProductController productController) {
        this.inventoryAdmin = inventoryAdmin;
        this.productoEditando = producto;
        this.productController = productController;
        initComponents();
        this.setLocationRelativeTo(null);
        cargarCategorias();
 
        if (productoEditando != null) {
            // Modo EDITAR: poblar los campos con los datos del producto
            jLabel1.setText("EDITAR PRODUCTO");
            NameTfld3.setText(productoEditando.getNombre());
            DescTfld1.setText(productoEditando.getDescripcion() != null ? productoEditando.getDescripcion() : "");
            PriceTxt2.setValue(productoEditando.getPrecio() != null ? productoEditando.getPrecio().longValue() : 0L);
            if (productoEditando.getPrecioOferta() != null) {
                OfferPriceTxt1.setValue(productoEditando.getPrecioOferta().longValue());
            }
            StockTxt1.setValue((long) productoEditando.getStock());
            seleccionarCategoria(productoEditando.getCategoriaId());
        } else {
            jLabel1.setText("AGREGAR PRODUCTO");
        }
    }
    
    //Carga las categorías desde la BD en el CategoryBox2.
    private void cargarCategorias() {
        List<Category> categorias = productController.obtenerCategorias();
        CategoryBox2.removeAllItems();
        for (Category cat : categorias) {
            CategoryBox2.addItem(cat.getNombre());
        }
    }
    
    //Selecciona en el ComboBox la categoría que corresponde al categoriaId del producto.
    private void seleccionarCategoria(int categoriaId) {
        List<Category> categorias = productController.obtenerCategorias();
        for (int i = 0; i < categorias.size(); i++) {
            if (categorias.get(i).getId() == categoriaId) {
                CategoryBox2.setSelectedIndex(i);
                return;
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NameTfld3 = new javax.swing.JTextField();
        DescTfld1 = new javax.swing.JTextField();
        CategoryBox2 = new javax.swing.JComboBox<>();
        PriceTxt2 = new javax.swing.JFormattedTextField();
        OfferPriceTxt1 = new javax.swing.JFormattedTextField();
        StockTxt1 = new javax.swing.JFormattedTextField();
        EnterBtn3 = new javax.swing.JButton();
        DeleteBtn2 = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENÚ INVENTARIO");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Precio:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Precio con oferta:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Categoría:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Stock:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Descripción:");

        DescTfld1.setToolTipText("");

        CategoryBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carnes frias", "Pescados", "Verduras", "Frutas", "Lacteos", "Bebidas", "Snacks" }));
        CategoryBox2.addActionListener(this::CategoryBox2ActionPerformed);

        PriceTxt2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        OfferPriceTxt1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        StockTxt1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PriceTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameTfld3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CategoryBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OfferPriceTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StockTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DescTfld1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 29, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(NameTfld3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescTfld1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CategoryBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PriceTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OfferPriceTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StockTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        EnterBtn3.setText("INGRESAR");
        EnterBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnterBtn3MouseClicked(evt);
            }
        });

        DeleteBtn2.setText("CANCELAR");
        DeleteBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBtn2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DeleteBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EnterBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DeleteBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CategoryBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoryBox2ActionPerformed

    private void EnterBtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnterBtn3MouseClicked
        String nombre         = NameTfld3.getText().trim();
        String descripcion    = DescTfld1.getText().trim();
        String categoria      = (String) CategoryBox2.getSelectedItem();
        String precioTexto    = PriceTxt2.getText().trim().replaceAll("[^0-9.]", "");
        String ofertaTexto    = OfferPriceTxt1.getText().trim().replaceAll("[^0-9.]", "");
        String stockTexto     = StockTxt1.getText().trim().replaceAll("[^0-9]", "");
 
        ProductController.SaveResult resultado;
 
        if (productoEditando == null) {
            // Modo AGREGAR
            resultado = productController.agregarProducto(
                nombre, descripcion, categoria, precioTexto, ofertaTexto, stockTexto
            );
        } else {
            // Modo EDITAR
            resultado = productController.actualizarProducto(
                productoEditando.getId(), nombre, descripcion, categoria,
                precioTexto, ofertaTexto, stockTexto
            );
        }
 
        switch (resultado) {
            case OK:
                javax.swing.JOptionPane.showMessageDialog(this,
                    (productoEditando == null ? "Producto agregado" : "Producto actualizado") + " correctamente.",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                if (inventoryAdmin != null) {
                    inventoryAdmin.refrescarTabla();
                    inventoryAdmin.setVisible(true);
                }
                this.dispose();
                break;
            case NOMBRE_VACIO:
                javax.swing.JOptionPane.showMessageDialog(this,
                    "El nombre del producto es obligatorio.",
                    "Campo vacío", javax.swing.JOptionPane.ERROR_MESSAGE);
                break;
            case PRECIO_INVALIDO:
                javax.swing.JOptionPane.showMessageDialog(this,
                    "El precio debe ser un número mayor a 0.",
                    "Precio inválido", javax.swing.JOptionPane.ERROR_MESSAGE);
                break;
            case STOCK_INVALIDO:
                javax.swing.JOptionPane.showMessageDialog(this,
                    "El stock debe ser un número mayor o igual a 0.",
                    "Stock inválido", javax.swing.JOptionPane.ERROR_MESSAGE);
                break;
            case NOMBRE_DUPLICADO:
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Ya existe un producto con ese nombre.",
                    "Nombre duplicado", javax.swing.JOptionPane.ERROR_MESSAGE);
                break;
            case ERROR_BD:
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al guardar en la base de datos. Intenta de nuevo.",
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                break;
        }

    }//GEN-LAST:event_EnterBtn3MouseClicked

    private void DeleteBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBtn2MouseClicked
        //CANCELAR: volver al InventoryAdmin sin guardar
        if (inventoryAdmin != null) {
            inventoryAdmin.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_DeleteBtn2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CategoryBox2;
    private javax.swing.JButton DeleteBtn2;
    private javax.swing.JTextField DescTfld1;
    private javax.swing.JButton EnterBtn3;
    private javax.swing.JTextField NameTfld3;
    private javax.swing.JFormattedTextField OfferPriceTxt1;
    private javax.swing.JFormattedTextField PriceTxt2;
    private javax.swing.JFormattedTextField StockTxt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
