/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.aaron.view;

import javax.swing.table.DefaultTableModel;
import mx.itson.aaron.controller.ProductController;
import mx.itson.aaron.model.Product;

/**
 *
 * @author Daniel
 */
public class InventoryAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InventoryAdmin.class.getName());
    private final ProductController productController = new ProductController();
    private javax.swing.JFrame framePadre;
    
    /**
     * Creates new form InventoryAdmin
     */
    public InventoryAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public InventoryAdmin(javax.swing.JFrame framePadre) {
        this.framePadre = framePadre;
        initComponents();
        this.setLocationRelativeTo(null);
        cargarTabla();
    }
    
    private void cargarTabla() {
        DefaultTableModel model = new DefaultTableModel(
            ProductController.COLUMNAS_INVENTARIO, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (Object[] fila : productController.getDataParaTabla()) {
            model.addRow(fila);
        }
        InventoryTbl1.setModel(model);
    }
    
    //Devuelve el ID del producto seleccionado en la tabla, o -1 si no hay selección.
    private int getProductoIdSeleccionado() {
        int fila = InventoryTbl1.getSelectedRow();
        if (fila < 0) return -1;
        return (int) InventoryTbl1.getValueAt(fila, 0); // Columna 0 = ID
    }
    
    //Llamado por Edit cuando guarda exitosamente, para refrescar la tabla.
    public void refrescarTabla() {
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InventoryTbl1 = new javax.swing.JTable();
        BackBtn3 = new javax.swing.JButton();
        AddBtn2 = new javax.swing.JButton();
        DeleteBtn2 = new javax.swing.JButton();
        EditBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Inventario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        InventoryTbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(InventoryTbl1);

        BackBtn3.setText("VOLVER");
        BackBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtn3MouseClicked(evt);
            }
        });
        BackBtn3.addActionListener(this::BackBtn3ActionPerformed);

        AddBtn2.setText("AGREGAR");
        AddBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtn2MouseClicked(evt);
            }
        });

        DeleteBtn2.setText("ELIMINAR");
        DeleteBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBtn2MouseClicked(evt);
            }
        });

        EditBtn1.setText("EDITAR");
        EditBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBtn1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BackBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DeleteBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EditBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtn3MouseClicked
        if (framePadre != null) {
            framePadre.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_BackBtn3MouseClicked

    private void BackBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtn3ActionPerformed

    private void AddBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtn2MouseClicked
        //Abre Edit en modo AGREGAR (sin producto)
        Edit editFrame = new Edit(this, null, productController);
        editFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddBtn2MouseClicked

    private void EditBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtn1MouseClicked
        int productoId = getProductoIdSeleccionado();
        if (productoId < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Selecciona un producto de la tabla para editar.",
                "Sin selección",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        Product producto = productController.buscarPorId(productoId);
        if (producto == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "No se pudo cargar el producto seleccionado.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
 
        // Abre Edit en modo EDITAR con el producto cargado
        Edit editFrame = new Edit(this, producto, productController);
        editFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EditBtn1MouseClicked

    private void DeleteBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBtn2MouseClicked
        int productoId = getProductoIdSeleccionado();
        if (productoId < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Selecciona un producto de la tabla para eliminar.",
                "Sin selección",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Estás seguro de que quieres eliminar este producto?\nEsta acción no se puede deshacer.",
            "Confirmar eliminación",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE);
 
        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;
 
        boolean ok = productController.eliminarProducto(productoId);
        if (ok) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Producto eliminado correctamente.",
                "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            cargarTabla();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "No se pudo eliminar el producto.\n" +
                "Puede que esté referenciado en una orden existente.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DeleteBtn2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn2;
    private javax.swing.JButton BackBtn3;
    private javax.swing.JButton DeleteBtn2;
    private javax.swing.JButton EditBtn1;
    private javax.swing.JTable InventoryTbl1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
